### ISSUE TITLE
Composer Cannot Install

### ISSUE THREAD

**Issue by ErikPartridge** [viraj-khatavkar/easy-slug#1]
Adding "easy-slug/easy-slug": "2.0._" to composer.json with laravel 5.0.16, concludes that it should uninstall laravel, because "easy-slug/easy-slug v2.0.0 requires illuminate/database 4._ -> satisfiable by illuminate/database[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9]", and none of those illuminate/database  are concluded to work with L5.

**Comment by viraj-khatavkar** [comment]
It is resolved now. Just update your composer. Before updating, restart git bash once, otherwise it will take it from cache
